apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  FAILURE_IMAGE_URL: "https://finalss.s3.amazonaws.com/failed.png"
  SUCCESS_IMAGE_URL: "https://finalss.s3.amazonaws.com/success.jpg"
 