apiVersion: v1
kind: ConfigMap
metadata:
  name: flaskapp-configmap
data:
  SUCCESS_IMAGE_URL: "https://finalss.s3.amazonaws.com/success.jpg"
  FAILURE_IMAGE_URL: "https://finalss.s3.amazonaws.com/failed.png"
  
 