apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  containers:
  - name: simple-webapp-mysql
    image: 754570389467.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:mysqlv1.1
    ports:
    - containerPort: 81
    env:
    - name: SUCCESS_IMAGE_URL
      valueFrom: 
        configMapKeyRef:
          name: flaskapp-configmap
          key: success
    - name: FAILURE_IMAGE_URL
      valueFrom: 
        configMapKeyRef:
          name: flaskapp-configmap
          key: failure
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
