apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flaskapp
  template:
    metadata:
      labels:
        name: flaskapp
    spec:
      serviceAccountName: clo835
      containers:
      - name: flaskapp
        image: 391837845833.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:mysqlv1.1
        ports:
        - containerPort: 81
        env:
        - name: SUCCESS_IMAGE_URL
          valueFrom: 
            configMapKeyRef:
              name: flaskapp-configmap
              key: SUCCESS_IMAGE_URL
        - name: FAILURE_IMAGE_URL
          valueFrom: 
            configMapKeyRef:
              name: flaskapp-configmap
              key: FAILURE_IMAGE_URL
        volumeMounts:
          - name: app-secret-volumes
            mountPath: "/opt/app-secret-volumes"
            readOnly: true
        envFrom:
           - secretRef:
               name: app-secret
      volumes:
        - name: app-secret-volumes
          secret:
            secretName: app-secret