apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv-pod
spec:
  volumes:
    - name: mysql-pvc
      persistentVolumeClaim:
        claimName: mysql-pvc
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
      volumeMounts:
        - mountPath: /data/db
          name: mysql-pvc