apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv-pod
spec:
  volumes:
    - name: mysql-pvc
      persistentVolumeClaim:
        claimName: mysql-pvc
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: app-secret
            key: DB_Password
            optional: false
      volumeMounts:
        - mountPath: /data/db
          name: mysql-pvc