apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
  replicas: 1
spec:
  containers:
  - name: simple-webapp-mysql
    image: kodekloud/simple-webapp-mysql
    ports:
    - containerPort: 81
    volumeMounts:
    - name:  webapp-pvc
      mountPath: "/data/db"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name:  webapp-pvc
      persistentVolumeClaim:
        claimName: webapp-pvc
      secret:
        secretName: app-secret