apiVersion: v1
kind: Pod
metadata:
  name: webapp-secret
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql 
    env:
    - name: secrets
      valueFrom: 
        configMapKeyRef:
          name: webapp-config
          key : HEADER
    name:  webapp-sqldp
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
  secret:
    secretName : password
